version: "3"

tasks:
  dev:
    cmds:
      - air
  docs:
    cmds:
      - swag init --dir ./cmd/http,./internal/router,./internal/handlers,./internal/database
  build:
    cmds:
      - go build -o build/pocket-garage-api cmd/http/main.go
  start:
    cmds:
      - ./build/pocket-garage-api
  install:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/go-task/task/v3/cmd/task@latest
